# Author: Daniel Yazgi
# Date: 2024-05-28
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
        stages: [pre-commit]
    -   id: end-of-file-fixer
        stages: [pre-commit]
    -   id: trailing-whitespace
        stages: [pre-commit]
-   repo: local
    hooks:
      - id: linting-hook
        name: linting-hook
        entry: ./hooks/linting_hook.sh
        language: script
        types: [python, yaml, toml]
        fail_fast: true
        pass_filenames: true
        stages: [pre-commit]     # Ensures it only runs during the commit stage
